# Run against all the files: pre-commit run -a
# Install the git hook scripts: pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-executables-have-shebangs

  - repo: local
    hooks:
      - id: ament_copyright
        name: fix copyright
        description: Check if copyright notice is available in all files.
        entry: ament_copyright --add-missing "Ekumen, Inc." apache2
        types_or: [c++, python]
        language: system

      - id: ament_flake8
        name: "check python format (flake8)"
        entry: ament_flake8
        exclude: (beluga|beluga_system_tests)\/
        types: [python]
        language: system

      - id: ament_pep257
        name: "check python format (pep257)"
        entry: ament_pep257
        exclude: (beluga|beluga_system_tests)\/
        types: [python]
        language: system

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.3
    hooks:
      - id: clang-format
        name: fix c++ format
        args: ["-style=file:.clang-format"]
        types: [c++]

  - repo: https://github.com/psf/black
    rev:  23.3.0
    hooks:
      - id: black
        name: "fix python format"
        entry: black --skip-string-normalization
