# Run against all the files: pre-commit run -a
# Install the git hook scripts: pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs

  - repo: local
    hooks:
      - id: ament_copyright
        name: Fix copyright
        description: Check if copyright notice is available in all files.
        entry: ament_copyright --add-missing "Ekumen, Inc." apache2
        types_or: [c++, python]
        language: system

      - id: beluga_compile_commands
        name: "[beluga] Export compile commands"
        description: Creates the compile_commands.json required by clang-tidy.
        entry: cmake -S ./beluga -B /tmp/beluga -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        fail_fast: true
        files: beluga\/
        types: [c++]
        pass_filenames: false
        language: system
      
      - id: beluga_system_tests_compile_commands
        name: "[beluga_system_tests] Export compile commands"
        description: Creates the compile_commands.json required by clang-tidy.
        entry: cmake -S ./beluga_system_tests -B /tmp/beluga_system_tests -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        fail_fast: true
        files: beluga_system_tests\/
        types: [c++]
        pass_filenames: false
        language: system

      - id: ament_uncrustify
        name: "[others] Fix C++ format (uncrustify)"
        entry: ament_uncrustify --reformat
        files: beluga_amcl\/
        types: [c++]
        language: system

      - id: ament_cpplint
        name: "[others] Check C++ format (cpplint)"
        entry: ament_cpplint
        files: beluga_amcl\/
        types: [c++]
        language: system

      - id: ament_flake8
        name: "[others] Check Python format (flake8)"
        entry: ament_flake8
        exclude: (beluga|beluga_system_tests)\/
        types: [python]
        language: system

      - id: ament_pep257
        name: "[others] Check Python format (pep257)"
        entry: ament_pep257
        exclude: (beluga|beluga_system_tests)\/
        types: [python]
        language: system

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
    - id: clang-format
      args: ["-style=file:.clang-format"]
      exclute: beluga_amcl\/
      types: [c++]

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        alias: beluga_clang_tidy
        args: [
          "-p=/tmp/beluga", "--fix",
          "-header-filter=.*", "--quiet", "-extra-arg=-std=c++17"
        ]
        files: beluga\/
        types: [c++]
      - id: clang-tidy
        alias: beluga_system_tests_clang_tidy
        args: [
          "-p=/tmp/beluga_system_tests", "--fix",
          "-header-filter=.*", "--quiet", "-extra-arg=-std=c++17"
        ]
        files: beluga_system_tests\/
        types: [c++]

  - repo: https://github.com/psf/black
    rev:  22.10.0
    hooks:
      - id: black
        name: "[others] Fix Python format (black)"
        entry: black --skip-string-normalization
