amcl:
  ros__parameters:
    alpha1: 0.1
    alpha2: 0.05
    alpha3: 0.1
    alpha4: 0.05
    global_frame_id: map
    odom_frame_id: odom
    base_frame_id: base
    map_topic: map
    scan_topic: scan
    initial_pose_topic: initialpose
    max_particles: 2000
    min_particles: 500
    pf_err: 0.05
    pf_z: 3.0
    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.001
    resample_interval: 1
    update_min_a: 0.2
    update_min_d: 0.25
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: 0.0
    max_beams: 100
    z_hit: 0.5
    z_rand: 0.5
    sigma_hit: 0.2
    transform_tolerance: 1.0
    initial_pose: [0, 2, 0]
    set_initial_pose: true
    execution_policy: seq
