amcl:
  ros__parameters:
    global_frame_id: map
    map_topic: map
    max_particles: 2000
    min_particles: 500
    pf_err: 0.05
    pf_z: 3.0
    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.001
    resample_interval: 1
    update_min_a: 0.2
    update_min_d: 0.25
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: 0.0
    z_hit: 0.5
    z_rand: 0.5
    sigma_hit: 0.2
